name: Bug report
description: Report a defect that affects users or developers.
title: 'bug: '
labels: ['type-bug']
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which package is affected?
      options:
        - prepaint
        - local-first
        - tx
        - playground
        - devtools
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong?
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: Browser/OS (e.g., Chrome 128, macOS 14.5)
