name: Feature request
description: Propose a change or improvement.
title: 'feat: '
labels: ['type-enhancement']
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which package would this affect?
      options:
        - prepaint
        - local-first
        - tx
        - demo
        - playground
        - devtools
        - other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem are we solving?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should we solve it?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you think about?
