export const DEFAULT_TTL_MS = 5 * 60 * 1000;

export const DEFAULT_TRANSACTION_TIMEOUT_MS = 30_000;

export const DEFAULT_MAX_BUFFER_SIZE = 500;

export const DEFAULT_RETRY_DELAY_MS = 100;

export const MAX_SNAPSHOT_AGE_MS = 24 * 60 * 60 * 1000;

export const DANGEROUS_HTML_TAGS = [
  'script',
  'iframe',
  'object',
  'embed',
  'form',
  'input',
  'button',
  'textarea',
  'select',
  'meta',
  'link',
  'base',
  'frame',
  'frameset',
] as const;

export const DANGEROUS_ATTRIBUTES = [
  'onload',
  'onerror',
  'onclick',
  'onmouseover',
  'onmouseout',
  'onmouseenter',
  'onmouseleave',
  'onfocus',
  'onblur',
  'onchange',
  'onsubmit',
  'onkeydown',
  'onkeyup',
  'onkeypress',
  'ontouchstart',
  'ontouchend',
  'ontouchmove',
  'onpointerdown',
  'onpointerup',
  'onpointermove',
  'ondrag',
  'ondrop',
  'ondragstart',
  'ondragend',
  'onanimationstart',
  'onanimationend',
  'onanimationiteration',
  'ontransitionend',
  'onwheel',
  'onscroll',
  'oncontextmenu',
  'oninput',
  'onreset',
  'onselect',
  'onabort',
  'oncanplay',
  'oncanplaythrough',
  'ondurationchange',
  'onemptied',
  'onended',
  'onloadeddata',
  'onloadedmetadata',
  'onloadstart',
  'onpause',
  'onplay',
  'onplaying',
  'onprogress',
  'onratechange',
  'onseeked',
  'onseeking',
  'onstalled',
  'onsuspend',
  'ontimeupdate',
  'onvolumechange',
  'onwaiting',
] as const;
