# .github/workflows/require-pr-labels.yml
name: Require PR labels
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, ready_for_review]
permissions:
  pull-requests: read
  statuses: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure one type: and exactly one area:"
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = (pr.labels || []).map(l => (l.name || '').toLowerCase());
            const typeLabels = labels.filter(n => n.startsWith('type: '));
            const areaLabels = labels.filter(n => n.startsWith('area: '));
            const problems = [];
            if (typeLabels.length < 1) problems.push('• Add at least one `type: ...` label.');
            if (areaLabels.length !== 1) problems.push('• Add exactly one `area: ...` label (prepaint | local-first | tx | demo | playground).');
            if (problems.length) {
              core.setFailed(['Missing required labels:', ...problems].join('\n'));
            } else {
              core.notice('Label check passed.');
            }
