name: Require PR Labels
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, ready_for_review]
permissions:
  pull-requests: read
  statuses: write
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "Ensure at least one type: and one area:"
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = (pr.labels || []).map(l => (l.name || '').toLowerCase());
            const hasType = labels.some(n => n.startsWith('type: '));
            const hasArea = labels.some(n => n.startsWith('area: '));
            let msg = [];
            if (!hasType) msg.push('• Add at least one `type: …` label (e.g., type: bug, enhancement, docs, test, chore, perf, refactor).');
            if (!hasArea) msg.push('• Add exactly one `area: …` label (demo | tx | prepaint | local-first).');
            if (msg.length) {
              core.setFailed(['Missing required labels:', ...msg].join('\n'));
            } else {
              core.notice('Label check passed ✅');
            }
